name: fast_downloader
description: Fast, cross-platform, cross platform download manager
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  path_provider: ^2.0.11
  flutter_svg: ^1.1.6
  clipboard: ^0.1.3
  file_picker: ^5.2.2
  loader_overlay: ^2.1.0
  flutter_spinkit: ^5.1.0
  provider: ^6.0.4
  pluto_grid: 5.4.0
  stream_channel: 2.1.1
  csv: ^5.0.1
  flutter_local_notifications: ^13.0.0
  uuid: ^3.0.7
  windows_notification: ^0.0.3
  url_launcher: ^6.1.10
  window_manager: ^0.3.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  number_inc_dec: ^0.8.0
  hotkey_manager: ^0.1.7


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/icons/all.svg
    - assets/icons/music.svg
    - assets/icons/video.svg
    - assets/icons/program.svg
    - assets/icons/archive.svg
    - assets/icons/document.svg
    - assets/icons/queue.svg
    - assets/icons/unfinished.svg
    - assets/icons/video_2.svg
    - assets/icons/file.svg
    - assets/icons/image.svg
    - assets/icons/logo.svg
    - assets/icons/github.svg
    - assets/icons/logo.png